name: Bootspec JSON Schema

on:
  push:
    branches: [main]

jobs:
  BuildAndPublishJsonSchemaDocs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: DeterminateSystems/determinate-nix-action@main
    - uses: DeterminateSystems/flakehub-cache-action@main
    - name: Set up GitHub Pages
      uses: actions/configure-pages@v5
    - name: Generate JSON Schema docs
      id: generate
      run: |
        mkdir -p dist
        nix develop --command generate-schema-doc --config expand_buttons=true schema.json dist/index.html
    - name: Upload docs
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./dist
    - name: Publish docs to GitHub Pages
      id: publish
      uses: actions/deploy-pages@v4
