name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check flake
        uses: DeterminateSystems/flake-checker-action
        with:
          fail-mode: true
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: true
      - name: Enable FlakeHub cache
        uses: DeterminateSystems/flakehub-cache-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
